import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-center"
          className="!left-[calc(50%-140px)]"
          toastOptions={{
            style: {
              background: "white",
              color: "black",
              border: "1px solid #e5e7eb",
            },
            classNames: {
              error: "bg-red-50 border-red-200 text-red-700",
              success: "bg-green-50 border-green-200 text-green-700",
              default: "bg-white border-gray-200 text-black",
            },
          }}
        />
      </body>
    </html>
  );
}
